// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIEDkneL9SXZwBVhqDmR53i0ULnZ50DXM',
    appId: '1:350277467736:web:50fdd4cc4cb2eeaf9c942d',
    messagingSenderId: '350277467736',
    projectId: 'authenticatu',
    authDomain: 'authenticatu.firebaseapp.com',
    storageBucket: 'authenticatu.firebasestorage.app',
    measurementId: 'G-41SHN6CL08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-JXhd_Juu3EyL887GusyGXJf5iO-F7go',
    appId: '1:350277467736:android:bc4db25d7b889f1d9c942d',
    messagingSenderId: '350277467736',
    projectId: 'authenticatu',
    storageBucket: 'authenticatu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd2br9n6MTZtI5gDiFqJjC4eQbeZn2THE',
    appId: '1:350277467736:ios:d8d35351ceaea3b29c942d',
    messagingSenderId: '350277467736',
    projectId: 'authenticatu',
    storageBucket: 'authenticatu.firebasestorage.app',
    iosClientId: '350277467736-h5k6aeccad12kabesi371878a0ajsv2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticatu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd2br9n6MTZtI5gDiFqJjC4eQbeZn2THE',
    appId: '1:350277467736:ios:d8d35351ceaea3b29c942d',
    messagingSenderId: '350277467736',
    projectId: 'authenticatu',
    storageBucket: 'authenticatu.firebasestorage.app',
    iosClientId: '350277467736-h5k6aeccad12kabesi371878a0ajsv2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticatu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIEDkneL9SXZwBVhqDmR53i0ULnZ50DXM',
    appId: '1:350277467736:web:a99cc23d3a7244969c942d',
    messagingSenderId: '350277467736',
    projectId: 'authenticatu',
    authDomain: 'authenticatu.firebaseapp.com',
    storageBucket: 'authenticatu.firebasestorage.app',
    measurementId: 'G-2XM6KY0GM1',
  );
}